
---
 - name: Launching aws ec2 instance
   hosts: localhost
   gather_facts: false
   tasks:
   - name: Launching ec2 instance with ec2 module 
     ec2:
      instance_type: t2.micro
      image: "{{ ami-ID }}"
      key_name: "{{ keyname }}"
      region: us-east-1
      instance_tags:
        Environment: testgit stat